<a href="https://colab.research.google.com/github/boradedeepak/ML_Models_trained/blob/main/Linear_regression_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

IMPORT LIBRARIES

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Import Dataset

In [ ]:
df = pd.read_csv('/content/regression_training_dataset.csv')
x = df.iloc[:, 1:-1]
y = df.iloc[:, -1]

Data preprocessing / Data cleaning

In [ ]:
df.describe()

       Experience_Years  Education_Level  ...  Projects_Completed   Salary_LPA
count       1000.000000      1000.000000  ...         1000.000000  1000.000000
mean           9.749000         2.980000  ...           24.471000    16.620590
std            6.062075         1.401272  ...           14.754554     4.706982
min            0.000000         1.000000  ...            0.000000     4.560000
25%            5.000000         2.000000  ...           12.000000    12.890000
50%           10.000000         3.000000  ...           24.000000    16.705000
75%           15.000000         4.000000  ...           37.000000    20.290000
max           20.000000         5.000000  ...           50.000000    28.290000

[8 rows x 5 columns]

In [ ]:
df.shape

(1000, 5)

In [ ]:
df.notnull().sum()

Experience_Years      1000
Education_Level       1000
Skill_Score           1000
Projects_Completed    1000
Salary_LPA            1000
dtype: int64

Splitting dataset into train - test set

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 0)

StandardScaler

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)

Linear regression on the training set

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

Visualisation

In [ ]:
y_pred = regressor.predict(x_test)
plt.scatter(y_train, regressor.predict(x_train), color = 'red')
plt.plot(y_test, regressor.predict(x_test), color = 'blue')
plt.title('Linear Regression')
plt.xlabel('y_test')
plt.ylabel('y_pred')
plt.show()